// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE7-4j-JrUBgtLsBra-VM96d_edKY0ziM',
    appId: '1:574607737304:web:c3aec85231c26f9b0c32ad',
    messagingSenderId: '574607737304',
    projectId: 'telkomsel-scanner',
    authDomain: 'telkomsel-scanner.firebaseapp.com',
    databaseURL: 'https://telkomsel-scanner-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'telkomsel-scanner.firebasestorage.app',
    measurementId: 'G-VQ36N6L3BV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7i5Y5XWjjnKTLHhAwHPgFsZpbhA6QmA4',
    appId: '1:574607737304:android:510672f58c7987ce0c32ad',
    messagingSenderId: '574607737304',
    projectId: 'telkomsel-scanner',
    databaseURL: 'https://telkomsel-scanner-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'telkomsel-scanner.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAFIkH03HYPNKcQ57BFvdHfyW89RW-eNU',
    appId: '1:574607737304:ios:2d9f2f6bbb93bcea0c32ad',
    messagingSenderId: '574607737304',
    projectId: 'telkomsel-scanner',
    databaseURL: 'https://telkomsel-scanner-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'telkomsel-scanner.firebasestorage.app',
    iosBundleId: 'com.example.tselScanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAFIkH03HYPNKcQ57BFvdHfyW89RW-eNU',
    appId: '1:574607737304:ios:2d9f2f6bbb93bcea0c32ad',
    messagingSenderId: '574607737304',
    projectId: 'telkomsel-scanner',
    databaseURL: 'https://telkomsel-scanner-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'telkomsel-scanner.firebasestorage.app',
    iosBundleId: 'com.example.tselScanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBE7-4j-JrUBgtLsBra-VM96d_edKY0ziM',
    appId: '1:574607737304:web:ec37927667999f510c32ad',
    messagingSenderId: '574607737304',
    projectId: 'telkomsel-scanner',
    authDomain: 'telkomsel-scanner.firebaseapp.com',
    databaseURL: 'https://telkomsel-scanner-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'telkomsel-scanner.firebasestorage.app',
    measurementId: 'G-0EVJX06N2C',
  );
}
